version: '3.8'

services:
  devcontainer:
    # build image from the Dockerfile in the .devcontainer directory
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    # image and container_name are not needed, but assign them so that VS code does not pick random names
    image: devcontainer
    container_name: devcontainer
    # mount source directory ($PWD) on the host at target path (home/pep/ride60-bootloader) in the container
    volumes:
    - ./my_volume_test:/root/home/my_work        #RADI
    # - $PWD/my_volume_test:/root/home/my_work   #RADI
    # - ../my_volume_test22:/root/home/my_work   #RADI - my_volume_test22 je jedan folder iznad od gdje je yml file

    # tells VS code which project to load (same as "target" from volumes)
    #command: sleep infinity
    hostname: localhost
    working_dir: /root/home/my_work/
    command: tail -f /dev/null
    privileged: true
